#!/bin/bash
while [ "$1" != '' ]
  do
    [ $1 == "" ] && sudo mcedit /etc/openwebrx/config_webrx.py && sdrrestart  && shift
    [ $1 == "config" ] && sudo mcedit /etc/openwebrx/config_webrx.py && sdrrestart  && shift
    [ $1 == "book" ] && sudo mcedit /etc/openwebrx/bookmarks.json && sdrrestart  && shift
    [ $1 == "band" ] && sudo mcedit /etc/openwebrx/bands.json && sdrrestart && shift
done
